name: Deploy MCP Knowledge Base Server

on:
  push:
    branches: [main]
    paths:
      - 'KnowledgeBase/**'
      - 'Docs/**'
      - '.github/workflows/deploy_mcp_server.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push MCP Knowledge Base Server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./KnowledgeBase/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/ugui-knowledge-base:latest
            ghcr.io/${{ github.actor }}/ugui-knowledge-base:${{ github.sha }}
          build-args: |
            DOCS_PATH=./Docs